version: '3.8'

services:
  # MongoDB database for development
  mongodb:
    image: mongo:7
    container_name: baton-mongodb-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=baton_user
      - MONGO_INITDB_ROOT_PASSWORD=baton_password
      - MONGO_INITDB_DATABASE=baton_dev
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - baton-network
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Development backend with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    container_name: baton-backend-dev
    ports:
      - "3001:3001"
      - "9229:9229" # Debug port
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://baton_user:baton_password@mongodb:27017/baton_dev?authSource=admin
      - CLIENT_URL=http://localhost:5173
      - MCP_SERVER_PORT=3002
      - BRIDGE_URL=http://172.18.0.1:8080
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
      # Exclude files that don't need to be watched
      - /app/.git
      - /app/dist
    user: root
    command: [
      "sh", "-c", 
      "echo '🚀 Starting Baton Backend Development Setup' && echo '📦 Installing dependencies...' && npm install && echo '🔧 Generating Prisma client...' && npx prisma generate && echo '✅ Setup complete!' && npm run dev"
    ]
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - baton-network

  # Development MCP Server with hot reload
  mcp-server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    container_name: baton-mcp-server-dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mongodb://baton_user:baton_password@mongodb:27017/baton_dev?authSource=admin
      - MCP_TRANSPORT_MODE=websocket
      - MCP_SERVER_PORT=3002
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
      # Exclude files that don't need to be watched
      - /app/.git
      - /app/dist
    user: root
    command: [
      "sh", "-c", 
      "echo '🚀 Starting Baton MCP Server Development Setup' && echo '📦 Installing dependencies...' && npm install && echo '🔧 Generating Prisma client...' && npx prisma generate && echo '✅ Setup complete!' && npm run mcp:dev:websocket"
    ]
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - baton-network

  # Development frontend with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
    container_name: baton-frontend-dev
    ports:
      - "5173:5173"
      - "5176:5174"  # HMR WebSocket port
    environment:
      - VITE_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      # Exclude files that don't need to be watched
      - /app/.git
      - /app/dist
    user: root
    command: [
      "sh", "-c", 
      "echo '📦 Installing dependencies...' && npm install && echo '✅ Dependencies installed!' && npm run dev -- --host 0.0.0.0"
    ]
    networks:
      - baton-network


volumes:
  mongodb_dev_data:

networks:
  baton-network: