version: '3.8'

services:
  # Development backend with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: development
    container_name: baton-backend-dev
    ports:
      - "3001:3001"
      - "9229:9229" # Debug port
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./data/baton.db
      - CLIENT_URL=http://localhost:5173
      - MCP_SERVER_PORT=3002
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend_data:/app/data
    command: ["npm", "run", "dev"]
    networks:
      - baton-network

  # Development frontend with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: development
    container_name: baton-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    networks:
      - baton-network

volumes:
  backend_data:

networks:
  baton-network: